### PR TITLE
typo

### PR DESCRIPTION
**Pull request by rynfelium**
small typo

### CODE REVIEW

**Review by vsiles — APPROVED** [review]
Good catch ! Thank you for the PR.

**Comment by vsiles** [comment]
@rynfelium Do you want to signup the CLA so I can merge your work, or should I commandeer it ?

**Comment by rynfelium** [comment]
I've already signed up right now, waiting for the confirmation (which might take a several minutes as per the doc), but feel free to do whatever you want :)

**Comment by rynfelium** [comment]
I opened another PR, and the CLA test was passed.

**Comment by vsiles** [comment]
> I opened another PR, and the CLA test was passed, you can merge that one, and close this PR.

Ok, will do !
Note that I can also rerun the test manually here, so next time, no need for cloning !

Thanks again

**Pull request closed without merging**
